version: '3.8'

services:
  node:
    build:
      context: .
      dockerfile: docker/Dockerfile.node
    volumes:
      - ./config:/app/config
      - ./logs/node:/app/logs
    environment:
      - CONFIG_PATH=/app/config/hydra.toml
    ports:
      - "52535:52535"
      - "52536:52536"
      - "52537:52537"
      - "55550:55550"
    command: ["/app/start.sh"]

  miner:
    build:
      context: .
      dockerfile: docker/Dockerfile.miner
    volumes:
      - ./config:/app/config
      - ./logs/miner:/app/logs
    environment:
      - CONFIG_PATH=/app/config/hydra.toml
      - WORKER_ID=1
      - NUM_THREADS=16
    ports:
      - "32525:32525"
    command: ["/app/start.sh"]