name: mazze
services:
  node:
    image: mazzelabs/mazze-chain:node-x86-64
    platform: linux/amd64
    volumes:
      - ./run/hydra.toml:/app/config/hydra.toml:ro
      - ./run/log.yaml:/app/config/log.yaml:ro
      - ./logs/node:/app/logs
    environment:
      CONFIG_PATH: /app/config/hydra.toml
    ports:
      - '55555:55555'
      - '52535:52535'
      - '52536:52536'
      - '52537:52537'
      - '58545:58545'
      - '58546:58546'
      - '32525:32525'
    command: ['/app/start.sh']

  miner:
    image: mazzelabs/mazze-chain:miner-x86-64
    platform: linux/amd64
    volumes:
      - ./run/hydra.toml:/app/config/hydra.toml:ro
      - ./run/log.yaml:/app/config/log.yaml:ro
      - ./logs/miner:/app/logs
    environment:
      CONFIG_PATH: /app/config/hydra.toml
      WORKER_ID: 1
      NUM_THREADS: 16
      STRATUM_HOST: node
      STRATUM_PORT: 32525
    command: ['/app/start.sh']
    depends_on:
      - node
