# Throttling value format:
#
# Token bucket: <max_tokens>,<init_tokens>,<recharge_rate>,<default_cost>,<max_throttled_tolerates>
#   max_tokens: maximum number of tokens in bucket.
#   init_tokens: number of tokens initialized in bucket.
#   recharge_rate: number of tokens recharged per second.
#   default_cost: number of tokens acquired at a time by default.
#   max_throttled_tolerates: maximum acquires allowed even throttled, otherwise client may be disconnected.

[sync_protocol]
Status="90,90,1,30,0" # heartbeat interval 30s
NewBlockHashes="200,200,20,1,100"
Transactions="50,50,10,1,50"
GetBlockHeaders="200,200,100,1,100"
NewBlock="20,20,4,1,20"
GetBlocks="200,200,100,1,50"
GetCompactBlocks="200,200,20,1,100"
GetBlockTxn="200,200,20,1,100"
DynamicCapabilityChange="20,20,5,1,30"
TransactionDigests="50,50,10,1,50"
GetTransactions="50,50,10,1,50"
GetTransactionsFromTxHashes="50,50,10,1,50"
GetBlockHashesByEpoch="50,50,10,1,50"
SnapshotManifestRequest="50,50,10,1,50"
SnapshotChunkRequest="50,50,10,1,50"
Throttled="100,100,10,1,50"

# Suggest to limit the IP address to access the RPC as well.
[rpc]
mazze_gasPrice="20,20,5,1,5"
mazze_epochNumber="20,20,5,1,5"
mazze_getBalance="50,50,10,1,5"
mazze_getCode="20,20,5,1,5"
mazze_getBlockByHash="20,20,5,1,5"
mazze_getBlockByHashWithMainAssumption="20,20,5,1,5"
mazze_getBlockByEpochNumber="20,20,5,1,5"
mazze_getBestBlockHash="50,50,10,1,5"
mazze_getNextNonce="50,50,10,1,5"
mazze_sendRawTransaction="50,50,10,1,5"
mazze_call="20,20,5,1,5"
mazze_getLogs="20,20,5,1,5"
mazze_getTransactionByHash="50,50,10,1,5"
mazze_estimateGas="10,10,2,1,1"
mazze_getBlocksByEpoch="20,20,5,1,5"
mazze_getTransactionReceipt="50,50,10,1,5"

[rpc_local]

[light_protocol]